# CONFIGURE FILE

## === COMMUNICATION ===
IP = "45.249.94.168"

VIDEO_PORT = 1145
DATA_PORT = 1419
CMD_PORT = 1981

CMD_ENCODE_FMT = "" # AP_V_ON, AP_HDG_ON, AP_H_ON, AP_VS_ON, AP_V_VAL, AP_HDG_VAL, AP_H_VAL, AP_VS_VAL, THR_L, THR_R, C_X, C_Y, GEAR_DOWN, 